### ISSUE TITLE
Roadmap?

### ISSUE THREAD

**Issue by hairychris** [bargst/pyethoff#3]
Is there a Roadmap of where you would like this project to go? I think it's important the Eth ecosystem is rich and healthy, it would be my pleasure to help out where I can.

**Comment by bargst** [comment]
Thanks for your proposed help, but for the moment this project is just my way to cold storage. So I add new feature as I need them.

On my roadmap is a document describing the way I setup an offline computer and key ceremony process using this project.

Have you some roadmap in mind ?
