### ISSUE TITLE
Wallet? Privkey?

### ISSUE THREAD

**Issue by reiven** [bargst/pyethoff#4]
Hi

I just want to know when you say _<path to wallet>_ in the README, what do this means? what that file contains?
I'm just wondering if i can sing just having an unsigned tx and the privatekey with this tool, is that possible?

Thanks

**Comment by bargst** [comment]
Yes this tool **was** able to sign a transaction with a file completely oflfine. 
But is now **not** up-to-date and in need of some serious maintenance ...
